//Assignmnetno 59:Write s program  for an exception with 5catches and 1 finally block
package asssign;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.InputMismatchException;
import java.util.Scanner;

public class assignmnetno59 {

	public static void main(String[] args) 
	{
try {
	Scanner s1=new Scanner(System.in);
	int s=s1.nextInt();
	int c=s/0;
	System.out.println(c);
}
	catch(InputMismatchException z)
	{
		System.out.println("this mismatch insput error");
	}
catch(ArithmeticException d)
{
	System.out.println("Arimatica exception");
}
	
catch(ArrayIndexOutOfBoundsException v)
{
	System.out.println("Exception outoofbound");
}
catch(NullPointerException b)
{
	System.out.println("Null ponter exception 1");
}

finally
{
	System.out.println("system database error");
}
	



	}

}
